cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('detail', views.detail, name='detail'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove/<int:product_id>/', views.remove, name='remove'),
    path('update', views.update, name='update'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
]

order/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'order'

urlpatterns = [
    path('load-cities/', views.load_cities, name='load_cities'),
    path('', views.order, name='order'),
]

cart/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.forms.models import model_to_dict
from django.views.decorators.http import require_http_methods
from shop.models import Product
from .cart import Cart


def detail(request):
    cart = Cart(request)
    
    return render(request,'cart/detail.html', {'cart': cart})

@require_http_methods(["POST"])
def add(request, product_id):
     product = get_object_or_404(Product, pk=product_id)
     cart = Cart(request)
     cart.add(product)

     return redirect('shop:product_item', id=product.id, slug=product.slug)

@require_http_methods(["POST"])
def update(request):
    cart = Cart(request)

    for item in cart:
        cart.update(item, request.POST[str(item.id)])

    return redirect('cart:detail')


def remove(request, product_id):
     product = get_object_or_404(Product, pk=product_id)
     cart = Cart(request)
     cart.remove(product)
     return redirect('cart:detail')




    
    

cart/templates/cart/detail.html
 {% extends "shop/base.html" %} {% block content %}
<div class="container">
    <form action="{% url "cart:update" %}" method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-header bg-dark text-light">
                Shopping cart
                <!-- <a href="" class="btn btn-outline-info btn-sm pull-right">Continiu shopping</a> -->
                <div class="clearfix"></div>
            </div>
            <div class="table-responsive">
                    <table class="table table-hover">
                            <thead class="text-muted">
                                <tr>
                                    <th scope="col" style="">Product</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                <tr>
                                    <td>
                                        <figure class="media">
                                            <div class="img-wrap">
                                                <img width="200" src="{{ item.main_image.url }}" >
                                            </div>
                                            <figcaption class="media-body ml-5">
                                                <h6 class="title text-truncate">{{ item.name }}</h6>
                                                <dl class="param param-inline small">
                                                    <dt>Description: </dt>
                                                    <dd>{{ item.description | truncatechars:180 | striptags  }} </dd>
                                                </dl>
                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        <select name="{{ item.id }}" class="form-control form-control-sm">
                                                {% for i in "xxxxxxxxxx" %}
                                                    <option {% if  forloop.counter  == item.quantity %} selected="selected" {% endif %}> {{ forloop.counter }}</option>
                                                {% endfor %}
                                        </select> 
                                    </td>
                                    <td>
                                        <div class="price-wrap">
                                            <var class="price"> ${{ item.total_price }}</var>
                                            <small class="text-muted">(${{ item.price }})</small>
                                        </div>
                                    </td>
                                    <td>
                                        <a href="{% url "cart:remove" item.id%}" class="btn btn-sm btn-outline-danger">Remove</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
            </div>
            <div class="card-footer">
                <!-- <div class="coupon col-md-5 col-sm-5  pull-left">
                    <div class="row">
                        <div class="col-6">
                            <input type="text" class="form-control" placeholder="cupone code">
                        </div>
                        <div class="col-6">
                            <input type="submit" class="btn btn-default" value="Use cupone">
                        </div>
                    </div>
                </div> -->
                <div class="pull-right">
                    <a href="{% url "order:order" %}" class="btn btn-sm btn-success pull-right">Checkout</a>
                    <button type="submit" class="btn btn-sm btn-outline-secondary pull-right mx-3">Update</button>
                    <div class="pull-right mt-2">
                        Total price:
                        <b>${{ cart.get_total_price }}</b>
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock %}