cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('detail', views.detail, name='detail'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove/<int:product_id>/', views.remove, name='remove'),
    path('update', views.update, name='update'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
]

order/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'order'

urlpatterns = [
    path('load-cities/', views.load_cities, name='load_cities'),
    path('', views.order, name='order'),
]

order/models.py
from django.db import models
from shop.models import Product
from cities_light.models import Country, City

class Order(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    paid = models.BooleanField(default=False)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.ForeignKey(City, on_delete=models.PROTECT, null=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Order {}'.format(self.id)
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    def create_mail(self, cart):
        mail = {}
        cartItems = ''

        for item in cart:
                cartItems += f"product: {item} quantity: {item.quantity}\n"

        mail['from_email'] = 'admin@myshop.com'
        mail['recipient_list'] = [self.email]
        mail['subject'] =  f"Order nr. {self.id}"
        mail['message'] = f"Dear {self.first_name},\n\nYou have successfully placed an order.\nYour order id is {self.id}. \n\n{cartItems}"

        return mail

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
            return '{}'.format(self.id)
    def get_cost(self):
        return self.price * self.quantity
        
    

order/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column,  ButtonHolder, HTML
from .models import Order
from cities_light.models import City

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city', 'country']
                  

class CustomFieldForm(OrderForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  
    
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('first_name',  css_class='form-group col-md-6 mb-0 '),
                Column('last_name', css_class='form-group col-md-6 mb-0 '),
                css_class='form-row'
            ),
            'email',
            'address', 
             Row(
                Column('country', css_class='form-group col-md-4 mb-0 '),
                Column('city', css_class='form-group col-md-4 mb-0 '),
                Column('postal_code', css_class='form-group col-md-4 mb-0 '),
                css_class='form-row'
            ),
            ButtonHolder(  
            HTML("<hr class='mb-4'>"),
            HTML("<button class='btn btn-primary btn-block' type='submit'> <i class='fa fa-credit-card'></i> Place order</button>") ),
        )

order/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from .forms import OrderForm, CustomFieldForm
from random import randint
from django.core.mail import send_mail
from cities_light.models import City
from django.contrib import messages 
from .models import OrderItem
from cart.cart import Cart

def order(request):
    if request.method == "POST":
        form = CustomFieldForm(request.POST)
        if form.is_valid():
            cart = Cart(request)
            order = form.save()
            
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item,
                                         price=item.price,
                                         quantity=item.quantity)

            mail = order.create_mail(cart)
            send_mail(**mail)
            cart.clear()

            return render(request,
                          'order/receipt.html',
                          {'order': order})
    else: 
        form = CustomFieldForm()
    return render(request,'order/order.html', {'form':  form})

def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'order/city_dropdown.html', {'cities': cities})
    
    

order/templates/order/city_dropdown.html
<option value=""></option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

order/templates/order/order.html
{% extends "shop/base.html" %} {% block content %} {% load crispy_forms_tags %}
<main id="main" role="main">
    <section id="checkout-container">
        <div class="container">
            <div class="row py-5">
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        <span class="badge badge-secondary badge-pill">{{ cart|length }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for item in cart %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ item.name }}</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted"> {{ item.quantity }}x ${{ item.price }}</span>
                        </li>
                        {% endfor %}
                        <!-- <li class="list-group-item d-flex justify-content-between bg-light">
                                <div class="text-success">
                                    <h6 class="my-0">Promo code</h6>
                                    <small>EXAMPLECODE</small>
                                </div>
                                <span class="text-success">-$5</span>
                            </li> -->
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>${{ cart.get_total_price }}</strong>
                        </li>
                    </ul>
                    <form class="card p-2">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Promo code">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-secondary">Redeem</button>
                            </div>
                        </div>
                    </form>
                    <div class="payment-methods">
                        <p class="pt-4 mb-2">Payment Options</p>
                        <hr>
                        <ul class="list-inline d-flex">
                            <li class="mx-1 text-info">
                                <i class="fa-2x fa fa-cc-visa"></i>
                            </li>
                            <li class="mx-1 text-info">
                                <i class="fa-2x fa fa-cc-stripe"></i>
                            </li>
                            <li class="mx-1 text-info">
                                <i class="fa-2x fa fa-cc-paypal"></i>
                            </li>
                            <li class="mx-1 text-info">
                                <i class="fa-2x fa fa-cc-jcb"></i>
                            </li>
                            <li class="mx-1 text-info">
                                <i class="fa-2x fa fa-cc-discover"></i>
                            </li>
                            <li class="mx-1 text-info">
                                <i class="fa-2x fa fa-cc-amex"></i>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8 order-md-1">
                    <form class="needs-validation" action="{% url "order:order" %}" method="POST" novalidate>
                        {% csrf_token %} 
                        {% crispy form %}
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %} {% block extra_js %}
<script>
    $(function () {
        $("#id_country").change(function (event) {
            var url = "load-cities"
            var countryId = $(this).val();  

            $.ajax({                       
                url: url,                    
                data: {
                    'country': countryId       
                },
                success: function (data) {   
                    $("#id_city").html(data);  
                }
            });

        });
    })

</script> {% endblock extra_js %}

order/templates/order/receipt.html
{% extends "shop/base.html" %} {% block content %}
<div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-xs-center">
                    <i class="fa fa-search-plus float-xs-left icon"></i>
                    <h2>Invoice for purchase #{{ order.id }}</h2>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card  height">
                            <div class="card-header">Shipping Address</div>
                            <div class="card-body">
                                <strong>{{ order.first_name }}:</strong><br>
                                {{ order.country.name }}<br>
                               {{ order.city.name }}<br>
                                {{ order.adress }}
                             {{ order.postal_code }}<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card ">
                    <div class="card-header text-center">
                        <h3 class="text-xs-center"><strong>Order summary</strong></h3>
                    </div>
                    <div class="card-block">
                        <div class="table-responsive">
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <td><strong>Item Name</strong></td>
                                        <td class="text-xs-center"><strong>Item Price</strong></td>
                                        <td class="text-xs-center"><strong>Item Quantity</strong></td>
                                        <td class="text-xs-right"><strong>Total</strong></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                        <tr>
                                            <td>{{ item.product.name }}</td>
                                            <td class="text-xs-center">${{ item.price }}</td>
                                            <td class="text-xs-center">{{ item.quantity }}</td>
                                            <td class="text-xs-right">${{ item.get_cost }}</td>
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <!-- <td class="emptyrow"><i class="fa fa-barcode iconbig"></i></td>
                                        <td class="emptyrow"></td> -->
                                        <td class="emptyrow text-xs-center"><strong>Total</strong></td>
                                        <td class="emptyrow text-xs-right">${{ order.get_total_cost }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <style>
    .height {
        min-height: 200px;
    }
    
    .icon {
        font-size: 47px;
        color: #5CB85C;
    }
    
    .iconbig {
        font-size: 77px;
        color: #5CB85C;
    }
    
    .table > tbody > tr > .emptyrow {
        border-top: none;
    }
    
    .table > thead > tr > .emptyrow {
        border-bottom: none;
    }
    
    .table > tbody > tr > .highrow {
        border-top: 3px solid;
    }
    </style>
    {% endblock %}