cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('detail', views.detail, name='detail'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove/<int:product_id>/', views.remove, name='remove'),
    path('update', views.update, name='update'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_item,
         name='product_item'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=100, unique=True, db_index = True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 null=True,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True, db_index = True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    description = models.TextField(blank=True)
    main_image = models.ImageField(upload_to='products_upload/', null=True) 
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
   

class ProductImage(models.Model):
    path = models.ImageField(upload_to='products_upload/')
    product = models.ForeignKey(Product,
                                 related_name='images',
                                 null=True,
                                 on_delete=models.CASCADE)

shop/views.py
from django.shortcuts import render
from .models import Product, ProductImage, Category
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.forms.models import model_to_dict

def product_list(request, category_slug=None):
    products = Product.objects.all()
    categories = Category.objects.all()
  
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,'shop/products_list.html', {
        'products': products, 
        'categories': categories
        })

def product_item(request, id, slug):
    random_products = Product.objects.all().exclude(pk=id).order_by('?')[:6]
    product = get_object_or_404(Product, pk=id)
    
    context = {
        'product': product, 
        'random_products': random_products
        }

    return render(request,'shop/product_item.html', context)

def find_state(request, id, slug):
    product = get_object_or_404(Product, pk=id)
    return render(request,'shop/product_item.html', {'product': product})
    
    

shop/templates/shop/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Shop{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/lux/bootstrap.min.css">
    <style>
        select.form-control:not([size]):not([multiple]) {
            height: auto!important;
        }   
        * {
            margin: 0;
        }

        html,
        body {
            height: 100%;
        }

        body {
            padding-top: 54px;
        }

        @media (min-width: 992px) {
            body {
                padding-top: 46px;
            }
        }


        #content {
            min-height: calc(100% - 90px);
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .footer {
            line-height: 50px;
        }

        .footer,
        #content:after {
            height: 50px;
            ;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark pt-2 pb-2 fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Shop</a>
            <div class="navbar pt-0 pb-0" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active p-2 bg-white mr-0">
                     {% with product_items=cart|length %}
                         {% if product_items %}
                          <a href="{% url "cart:detail" %}">
                             {{ product_items }} item{{ product_items|pluralize }}
                            ${{ cart.get_total_price }}
                          </a>
                             {% else %}
                                Your cart is empty.
                         {% endif %}
                    {% endwith %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div id="content">
        {% block content %} {% endblock %}
    </div>
    <footer class="footer  bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; shop</p>
        </div>
    </footer>
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock extra_js %}
</body>
</html>

shop/templates/shop/product_item.html
{% extends "shop/base.html" %}
{% block content %}
    <div class="container">
      <div class="row mt-4">
        <div class="col-lg-2">
          <div class="d-none d-lg-block">
              <div class="row ">
                  <p class="font-weight-bold">People also bought</p>
                  {% for product in random_products %}
                  <div class="col-lg-6 pr-1 pl-1" style="border: none;" >
                      <a href="/{{ product.id }}/{{ product.slug }}">
                        <img class="img-fluid mb-1"   src="{{ product.main_image.url }}" alt="image cap"></a>
                    </div>
                  {% endfor %}
                </div>
          </div>
        </div>
        <div class="col-lg-10">
          <div class="card">
            <di class="row">
                <div class="text-center col-lg-7"> 
                    <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for img in product.images.all %}
                            <li data-target="#carouselIndicators" data-slide-to="0" class="{% if forloop.first %} active {% endif %}"></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">
                            {% for img in product.images.all %}
                            <div class="carousel-item {% if forloop.first %} active {% endif %}">
                                <img class="d-block w-100"  src="{{ img.path.url }}" >
                            </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div>
                </div>
                <div class="col-lg-5"> 
                    <div class="card-body ml-3 pl-0 pr-0">
                            <h3 class="card-title">
                                {{ product.name }}
                            </h3>
                        <h4>${{ product.price }}</h4>
                        <div class="card-text" style="white-space: pre-wrap;">{{ product.description | safe }}</div>
                        <form class="col-lg-6 p-0 mt-3" action="{% url "cart:add" product.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Add to cart">
                        </form>
                      </div>
                </div>
            </div>

          </div>
        </div>
      </div>
    </div>
{% endblock %}

shop/templates/shop/products_list.html
{% extends "shop/base.html" %} {% load static %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <h1 class="my-4">Shop</h1>
      <div class="list-group mb-4">
        <a href="/" class="list-group-item"> All</a>
        {% for category in categories %}
        <a href="/{{ category.slug }}" class="list-group-item">{{ category.name }}
        </a>
        {% endfor %}
      </div>
    </div>
    <div class="col-lg-9">
      <!-- <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <img class="d-block" style="max-height: 420px; width: 100%" src="{% static "images/front-img.jpg" %}" alt="First slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div> -->
      <div class="row">
        {% for product in products %}
        <div class="col-md-6 mb-4">
          <div class="card h-100">
            <a href="/{{ product.id }}/{{ product.slug }}/">
              <img class="card-img-top" src="{{ product.main_image.url }}" alt="" />
            </a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="/{{ product.id }}/{{ product.slug }}">{{ product.name }}
                </a>
              </h4>
              <h5>${{ product.price }}</h5>
              <p class="card-text">
                {{ product.description | truncatechars:180 | striptags }}
              </p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}